name: モデルトレーニング＆シミュレーション

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動での実行も可能にします

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v2

    - name: Pythonのセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 使用するPythonのバージョン

    - name: 必要なライブラリのインストール
      run: |
        pip install lightgbm keras pandas jpholiday scikit-learn matplotlib tqdm

    - name: ディレクトリ移動とリポジトリセットアップ
      run: |
        git clone https://github.com/Ry02024/EBProM.git
        cd EBProM/Modules

    - name: データ前処理の実行
      run: |
        python preprocess.py  # 前処理を行うスクリプト

    - name: モデルトレーニングの実行
      run: |
        python train_model.py  # モデルをトレーニングするスクリプト

    # - name: シミュレーションの実行と評価
    #   run: |
    #     python simulation.py  # シミュレーションを実行するスクリプト

    # - name: モデル保存と結果のコミット
    #   run: |
    #     git config --local user.email "you@example.com"
    #     git config --local user.name "GitHub Actions"
    #     git add .
    #     git commit -m "新しいモデルと結果をコミット"
    #     git push
