name: モデルトレーニング＆シミュレーション

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動での実行も可能にします

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v2

    - name: Pythonのセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 使用するPythonのバージョン

    - name: 必要なライブラリのインストール
      run: |
        pip install -r requirements.txt

    - name: ディレクトリ移動とリポジトリセットアップ
      run: |
        git clone https://github.com/Ry02024/EBProM.git
        cd EBProM

    - name: データ前処理の実行
      run: |
        python Modules/utils.py  # 前処理を行うスクリプト

    # - name: モデルトレーニングの実行
    #   run: |
    #     python Modules/machine_learning.py  # モデルをトレーニングするスクリプト

    # - name: シミュレーションの実行と評価
    #   run: |
    #     python simulation.py  # シミュレーションを実行するスクリプト

    - name: 前処理結果をコミットしてプッシュ
      run: |
        git config --local user.email "tan0ry02024@gmail.com"
        git config --local user.name "Ry02024"
        git add Data/Preprocess/preprocess.csv  # 前処理結果ファイルを追加
        git commit -m "前処理結果を追加"
        git push
